---
title: Ariadne's Thread
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ''
baseurl: ''
github_username: AriadneThread
favicon: "/assets/images/favicon.ico"
website: http://www.zhidianwuxian.cn
company_name: 指点无限（北京）科技有限公司
markdown: kramdown
permalink: "/:year/:month/:day/:title.html"
exclude:
- vendor
